CREATE DATABASE IF NOT EXISTS clients;

CREATE USER 'godel'@'%' IDENTIFIED BY 'password123';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `clients`.* TO 'godel'@'%';

FLUSH PRIVILEGES;
